### ISSUE TITLE
whats the ban chance of using each type of macro?

### ISSUE THREAD

**Issue by JacobLDot** [Cephetir/SkySkipped#106]
whats the ban chance of using each type of macro? I honestly don't know anything about macros, and I don't wanna get banned since its my last ban attempt, uhhhh so please let me know how to safely use this mod without getting banned.

**Comment by th1ccpineapple** [comment]
Hey Jacob! The gemstone macro skyskipped sells is the safest and most reliable (somewhat) in the market. The macro does ban, but only through admin specs- watchdog can’t detect it. There’s no real way for the macro to prevent all bans, but everything should be alright if you stay at your pc. Good luck

**Comment by bibufr** [comment]
what he said 🗣️🗣️🗣️
