### ISSUE TITLE
GOT ME WIPED

### ISSUE THREAD

**Issue by Zenakin-1777** [Cephetir/SkySkipped#107]
I was using the coflnet auctionflipper that came with SkySkipped under the "Hacks" tab and whilst there were a few bugs, like sometimes it didn't properly relist items, it was fine and did a good enough job, but I got curious about what the "Skip" option did, since there was no description for it, and as soon as I enabled it, on the very first snipe, it got instantly banned, and the profile got wiped..
![SkySkipped_Wipe](https://github.com/Cephetir/SkySkipped/assets/154721632/eaa54199-e86d-4ec8-97f2-8c7b08754cca)

**Comment by Cephetir** [comment]
Skill issue, should have asked in discord server

**Comment by Zenakin-1777** [comment]
Can't verify in the discord server, the website link gets blocked by both
chrome AND my isp for being unsecure :/

**Comment by Zenakin-1777** [comment]
The verify.skyskipped.com link

**Comment by Zenakin-1777** [comment]
Joined out of my home network, now it's fine. Nice fast responses too ty👍

**Comment by TreXito** [comment]
this thread is so funny
