### ISSUE TITLE
[Not Urgent] Typo (dugeons)

### ISSUE THREAD

**Issue by WitheredFOT** [Cephetir/SkySkipped#109]
dugeons
![image](https://github.com/Cephetir/SkySkipped/assets/101938430/520fa0ae-12cd-4b98-a880-7e3d94bf4264)

**Comment by cozyuwu** [comment]
Im pretty sure thats ment to be like that

**Comment by May2Beez** [comment]
That's a proper spelling

**Comment by WitheredFOT** [comment]
oh lol
