### ISSUE TITLE
Wrong update download

### ISSUE THREAD

**Issue by Sylvezar** [Cephetir/SkySkipped#65]
https://github.com/Cephetir/SkySkipped/blob/kotlin/src/main/kotlin/me/cephetir/skyskipped/SkySkipped.kt line 104 has the wrong github repo as the download for the newest update

**Comment by Cephetir** [comment]
> https://github.com/Cephetir/SkySkipped/blob/kotlin/src/main/kotlin/me/cephetir/skyskipped/SkySkipped.kt line 104 has the wrong github repo as the download for the newest update

Holy shit ty lol

**Comment by Cephetir** [comment]
But its better as is
