### ISSUE TITLE
Keep getting this:

### ISSUE THREAD

**Issue by UltimateBoi** [Cephetir/SkySkipped#76]
![image](https://user-images.githubusercontent.com/63293118/173226847-33f03bef-5c8f-418d-bad0-bcb5a4bb8083.png)

ive selected every option i need to in macro and it still dont start.

**Comment by Cephetir** [comment]
Reselect nether wart macro in config (press it again)

**Comment by UltimateBoi** [comment]
i did

**Comment by UltimateBoi** [comment]
nvm srry
it works now tjhank!
