### ISSUE TITLE
Crash when launching with Fabric + Forge

### ISSUE THREAD

**Issue by DaCreeperGuy** [Cephetir/SkySkipped#78]
No logs just crashes with error 545

Discord: Emzy#1234

**Comment by Cephetir** [comment]
Use forge 1.8.9, wth is fabric + forge?

**Comment by DaCreeperGuy** [comment]
You can install Forge and Fabric at the same time on MultiMC and maybe its the backwards comp plugin for forge but I guess I will just use normal 1.8.9 Forge
